package ca.sheridancollege.acevedpa.domain;

public enum Categories {
	CONFERENCE, SEMINAR, NETWORKING, FESTIVAL,
	FUNDRAISING, MUSIC, ARTS, PERFORMANCE, LECUTRE,
	FASHION, KIDS_AND_FAMILY, SPORTS, FOOD_AND_DRINK,
	FILM, CONCERT, TECHNOLOGY
}
